JEIEvents.hideItems( event => {
  event.hide('createaddition:copper_rod')
  event.hide('createaddition:gold_rod')
  event.hide('createaddition:iron_rod')
  event.hide('createaddition:brass_rod')
  event.hide('createaddition:chocolate_cake')
  event.hide('createaddition:honey_cake')
  event.hide('createaddition:diamond_grit_sandpaper')
  event.hide('createaddition:diamond_grit')
  event.hide('createaddition:seed_oil_bucket')
  event.hide('createaddition:bioethanol_bucket')
  event.hide('createaddition:electric_motor')
  event.hide('createaddition:alternator')
  event.hide('createaddition:electrum_nugget')
  event.hide('createaddition:zinc_sheet')
  event.hide('createaddition:straw')
  event.hide('createaddition:electrum_amulet')
  event.hide('createaddition:gold_spool')
})

JEIEvents.hideFluids ( event => {
  event.hide('createaddition:seed_oil')
  event.hide('createaddition:bioethanol')
})

