ServerEvents.recipes(event  => {

  event.remove({ id: 'createdieselgenerators:crafting/engine_piston' })
  event.remove({ id: 'createdieselgenerators:crafting/engine_piston_from_rods' })
  event.remove({ id: 'createdieselgenerators:crafting/engine_silencer' })
  event.remove({ id: 'createdieselgenerators:crafting/engine_turbocharger' })
  event.remove({ id: 'createdieselgenerators:compacting/plant_oil' })
  event.remove({ id: 'createaddition:compacting/seed_oil' })
  event.remove({ id: 'createdieselgenerators:mixing/biodiesel' })
  event.remove({ mod:'createdieselgenerators', type: "createdieselgenerators:basin_fermenting" })
  event.remove({ id: 'createdieselgenerators:crafting/diesel_engine' })
  event.remove({ id: 'createdieselgenerators:crafting/large_diesel_engine' })
  event.remove({ id: 'createdieselgenerators:crafting/huge_diesel_engine' })
  event.remove({ id: 'createdieselgenerators:crafting/pumpjack_hole' })
  event.remove({ id: 'createdieselgenerators:crafting/pumpjack_bearing' })
  event.remove({ id: 'createdieselgenerators:crafting/pumpjack_head' })
  event.remove({ id: 'createdieselgenerators:crafting/kelp_handle' })
  event.remove({ id: 'createdieselgenerators:mechanical_crafting/pumpjack_crank' })
  event.remove({ mod:'createdieselgenerators', output: 'createdieselgenerators:chemical_sprayer' })
  event.remove({ id: 'createdieselgenerators:crafting/canister' })
  event.remove({ id: 'createdieselgenerators:crafting/oil_barrel' })
  event.remove({ id: 'createdieselgenerators:crafting/lighter' })

})